ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/serial/by-path/platform-fc880000.usb-usb-0:1.2:1.0-port0   
    frame_id: ydlidar2
    ignore_array: ""
    baudrate: 230400
    lidar_type: 1
    device_type: 0
    sample_rate: 4
    intensity_bit: 8
    abnormal_check_count: 4
    fixed_resolution: true
    reversion: true
    inverted: true
    auto_reconnect: true
    isSingleChannel: false
    intensity: true
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 12.0
    range_min: 0.001
    frequency: 10.0
    invalid_range_is_inf: false